version: '3.8'

services:
  neo4j:
    image: neo4j:5.15-community
    container_name: ginko-neo4j-dev
    ports:
      - "7474:7474"  # HTTP (Neo4j Browser)
      - "7687:7687"  # Bolt protocol (driver connections)
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    environment:
      # Authentication (change these in production!)
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-devpassword123}

      # Memory configuration (tune based on your machine)
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=2G
      - NEO4J_server_memory_pagecache_size=1G

      # APOC plugin (useful for graph algorithms)
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*

      # Allow remote connections (development only!)
      - NEO4J_server_default__listen__address=0.0.0.0

      # Increase transaction timeout for large imports
      - NEO4J_db_transaction_timeout=60s

    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s

    restart: unless-stopped

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local
